FROM eclipse-temurin:21-jre-jammy@sha256:eebd356ad7358b7094758e5787a6726f332917cfd56feab6457c56dab895cdbf

COPY distribution /opt/bounded-origin
COPY test-classes /opt/smoke/test-classes
COPY smoke.yaml /etc/bounded-origin/smoke.yaml
